version: '3.8'
services:
  poc-cce-database:
    image: postgres:latest
    environment:
      POSTGRES_DB: poc-cce
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

  poc-cce-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  otel-collector:
    image: otel/opentelemetry-collector
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./configs/otel-config.yml:/etc/otel-config.yml
    command:
      - --config=/etc/otel-config.yml

  tempo:
    image: grafana/tempo
    ports:
      - "3100:3100"
      - "9095"
      - "4317"
      - "4318"
    volumes:
      - ./configs/tempo-config.yml:/etc/tempo-config.yml
    command:
      - -config.file=/etc/tempo-config.yml

  poc-cce-directory-service:
    image: sebastianbran/poc-cce-directory-service:latest
    depends_on:
      - poc-cce-database
    environment:
      ENV: prod
      DB_HOST: poc-cce-database
      DB_PORT: 5432
      DB_NAME: poc-cce
      DB_USER: admin
      DB_PASSWORD: admin123
      REDIS_HOST: poc-cce-redis
      REDIS_PORT: 6379
      OTEL_SERVICE_NAME: directory-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    ports:
      - "8080:8080"