spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: directory
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/directory/**
            - id: transaction
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/transaction/**
            - id: notification
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/notification/**