server:
  port: 8082

spring:
  application:
    name: api-gateway
  profiles:
    active: ${ENV}

logging:
  pattern:
    level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p"

management:
  tracing:
    sampling:
      probability: 1
