spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/poc-cce
    username: admin
    password: admin123
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: poc-cce
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/poc-cce
