version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8082:80"
    depends_on:
      - directory-service
      - transaction-service
      - notification-service

  directory-service:
    image: sebastianbran/poc-cce-directory-service:latest
    depends_on:
      - database
    environment:
      ENV: prod
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: poc-cce
      DB_USER: admin
      DB_PASSWORD: admin123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OTEL_SERVICE_NAME: directory-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OAUTH2_JWT_ISSUER_URI: http://keycloak:8080/realms/poc-cce
    expose:
      - "8080"

  transaction-service:
    image: sebastianbran/poc-cce-transaction-service:latest
    depends_on:
      - database
    environment:
      ENV: prod
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: poc-cce
      DB_USER: admin
      DB_PASSWORD: admin123
      REST_CLIENT_API_GATEWAY_BASE_URL: http://api-gateway:80
      OTEL_SERVICE_NAME: transaction-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      OAUTH2_JWT_ISSUER_URI: http://keycloak:8080/realms/poc-cce
      # IBM MQ settings
      # comment these lines if you don't want to use IBM MQ, specially on Apple M1/M2/M3/M4 chips
      MQ_QMGR: POC.CCE
      MQ_CHANNEL: DEV.APP.SVRCONN
      MQ_CONN_NAME: ibm-mq(1414)
      MQ_APP_USER: app
      MQ_APP_PASSWORD: admin
      MQ_QUEUE_OUT: DEV.QUEUE.1
    expose:
      - "8081"

  notification-service:
    image: sebastianbran/poc-cce-notification-service:latest
    depends_on:
      - database
    environment:
      ENV: prod
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: poc-cce
      DB_USER: admin
      DB_PASSWORD: admin123
      OTEL_SERVICE_NAME: notification-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      OAUTH2_JWT_ISSUER_URI: http://keycloak:8080/realms/poc-cce
    expose:
      - "8083"

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: poc-cce
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    expose:
      - "6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    expose:
      - "4317"
      - "8889"
    volumes:
      - ./configs/otel-config.yml:/etc/otel-config.yml
    command:
      - --config=/etc/otel-config.yml

  tempo:
    image: grafana/tempo:latest
    expose:
      - "3100"
      - "9095"
      - "4317"
    volumes:
      - ./configs/tempo-config.yml:/etc/tempo-config.yml
    command:
      - -config.file=/etc/tempo-config.yml

  loki:
    image: grafana/loki:latest
    expose:
      - "3100"
    volumes:
      - ./configs/loki-config.yml:/etc/loki-config.yml
    command:
      - -config.file=/etc/loki-config.yml

  prometheus:
    image: prom/prometheus:latest
    expose:
      - "9090"
    volumes:
      - ./configs/prometheus-config.yml:/etc/prometheus-config.yml
    command:
      - --config.file=/etc/prometheus-config.yml

  kafka:
    image: apache/kafka-native:latest
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    expose:
      - "9092"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    ports:
      - "8080:8080"

  # this image does not work on Apple M1/M2/M3/M4 chips
  # comment this section if you don't want to use IBM MQ, specially on Apple M1/M2/M3/M4 chips
  ibm-mq:
    image: icr.io/ibm-messaging/mq:latest
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: POC.CCE
      MQ_APP_PASSWORD: admin
      MQ_ADMIN_PASSWORD: admin
    expose:
      - "1414"
      - "9443"
    ports:
      - "9944:9443"
