apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: sebastianbran/poc-cce-notification-service:latest
          env:
            - name: ENV
              value: prod
            - name: DB_HOST
              value: database-svc
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: poc-cce
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin123
            - name: REDIS_HOST
              value: redis-svc
            - name: REDIS_PORT
              value: "6379"
            - name: OTEL_SERVICE_NAME
              value: notification-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector-svc:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-svc
spec:
  type: LoadBalancer
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
