apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-cce-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-cce-database
  template:
    metadata:
      labels:
        app: poc-cce-database
    spec:
      containers:
        - name: database
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: poc-cce
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin123
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: poc-cce-database-svc
spec:
  selector:
    app: poc-cce-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432