apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: sebastianbran/poc-cce-transaction-service:latest
          env:
            - name: ENV
              value: prod
            - name: DB_HOST
              value: database-svc
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: poc-cce
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin123
            - name: REST_CLIENT_API_GATEWAY_BASE_URL
              value: http://api-gateway-svc:8082
            - name: OTEL_SERVICE_NAME
              value: transaction-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector-svc:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-svc:9092
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service-svc
spec:
  type: LoadBalancer
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
