server:
  port: 8081

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/poc-cce
    username: admin
    password: admin123
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: poc-cce
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/poc-cce

rest:
  client:
    directory-service: http://localhost:8080

ibm:
  mq:
    queueManager: POC.CCE
    channel: DEV.APP.SVRCONN
    connName: ibm-mq-svc(1414)
    user: app
    password: admin

app:
  mq:
    queueOut: DEV.QUEUE.1