spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/poc-cce
    username: admin
    password: admin123

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
