spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/poc-cce
    username: admin
    password: admin123
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/poc-cce