server:
  port: 8080

spring:
  application:
    name: directory
  profiles:
    active: ${ENV}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
  pattern:
    level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p"

management:
  tracing:
    sampling:
      probability: 1
